[package]
name = "hypercube"
version = "0.1.0"

[dependencies]
rand = "0.5.4"
stdweb = "0.4.10"
stdweb-derive = "0.5.1"
serde = "1.0.0"
serde_derive = "1.0.0"

itertools = "0.7.8"
nalgebra = "0.16.10"

[build-dependencies]
webgl_generator = "0.2.0"